# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          repository: llvm/llvm-project
          fetch-depth: 1

      # Runs a set of commands using the runners shell
      - name: build
        run: |        
          #          sudo apt update && sudo apt install -y  gcc g++ cmake ninja-build git python3 zlib1g-dev
          mkdir build
          cd build
          cmake -G Ninja -DLLVM_ENABLE_PROJECTS='clang;clang-tools-extra' -DLLVM_ENABLE_RUNTIMES='libcxx;libcxxabi' -DLIBCXXABI_USE_LLVM_UNWINDER=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/myclang -DLLVM_TARGETS_TO_BUILD='Native' ../llvm
          ninja install


      - name: Upload
        uses: actions/upload-artifact@v4
        with:
      # Artifact name
          name: myartifact
          path: /opt/myclang 
